#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

ALL_STAGED=$(git diff --name-only --cached --diff-filter=d)
STAGED_FILES_TO_LINT=$(git diff --name-only --cached --diff-filter=d -- "*.ts")
STAGED_PKGS=$(git diff --name-only --cached --diff-filter=d -- "package.json")

if [[ -n $STAGED_FILES_TO_LINT ]]; then yarn eslint --fix -f pretty $STAGED_FILES_TO_LINT; fi
if [[ -n $ALL_STAGED ]]; then yarn pretty-quick --staged --fix && git add $ALL_STAGED; fi

# If packages are updated, check that versions are aligned
if [[ -n $STAGED_PKGS ]]; then yarn prettier-package-json --config .prettierrc --write $STAGED_PKGS || exit 0; fi
